Clean docstring left from example
tmrowco/electricitymap-contrib pull request #3100
Opened 2021-04-19 11:11 UTC by yuvalabou

added annotations where neccessary

2021-04-28 11:14 UTC, madsnedergaard requested changes
Hi @yuvalabou, thanks for doing this - it's pretty nice to get this cleaned up and we really appreciate the thorough work! 💪 

I think it would be nice to keep some of the comments about returned values. Even though it can often be inferred from the return type (and thanks for adding those!), there are some cases where the comments give additional context that is nice. I have added comments for some of those, but probably missed some (it's a pretty big PR 😉).

So I'd suggest the following:
- [x] Remove all the copied examples 
- [x] Remove useless comments about returns (e.g. `Returns a dictionary.`)
- [ ] Keep comments that are more detailed than the return type (e.g. `:return: (int) index of the newest data or -1 if no data (empty day)`) (you have to read through the code to find the "-1" part)

2021-04-28 11:14 UTC, madsnedergaard commented on parsers/NI.py
> -    :return: tuple(production, datetime_datetime)
Worth keeping.

2021-04-28 11:14 UTC, madsnedergaard commented on parsers/TR.py
> -    :return: (int) index of the newest data or -1 if no data (empty day)
Worth keeping.

2021-04-28 11:14 UTC, madsnedergaard commented on parsers/US_NY.py
> -    Maps to type and returns a list of tuples containing datetime string and production.
Worth keeping.

2021-04-28 11:14 UTC, madsnedergaard commented on parsers/BD.py
> -    Returns a list of 2 element tuples in form (dict, arrow object)."""
Worth keeping.

2021-04-28 19:30 UTC, skovhus commented
This PR is not getting easier to review after all the unrelated formatting changes...

It would be great if we could limit the scope to only be about removal of redundant doc strings and some type annotations. 

About the formatting changes: Dis you used a formatter, like Black, or manually formatted the code?

2021-04-28 20:16 UTC, yuvalabou commented
I didn't use any formatter as it would result in massive changes to all files, every change I did by hand and indeed tried not to get carried away.

But I do agree, I will revert some of them and make a different PR for some of the more format related changes.

2021-04-29 06:20 UTC, skovhus commented
> But I do agree, I will revert some of them and make a different PR for some of the more format related changes.

Thanks! :)

2021-06-17 04:33 UTC, skovhus commented on parsers/KR.py
> +def check_hydro_capacity(plant_name, value, logger) -> True | ValueError:
```suggestion
def check_hydro_capacity(plant_name, value, logger) -> bool | ValueError:
```

2021-06-17 07:45 UTC, skovhus approved these changes
I've looked through the changes. This took a bit of time as the PR is fairly big. :D 

@madsnedergaard when you have time, it would be great if you could double check.

2021-06-17 11:03 UTC, madsnedergaard approved these changes
Went through everything again and it looks good to me! 
It's really nice to get all the parsers cleaned up, so thanks for doing this! 🙏

2021-06-18 08:16 UTC, merged