Add "lowCarbDescription" locale in PL
tmrowco/electricitymap-contrib pull request #3355
Opened 2021-09-05 06:38 UTC by cieciurm

Hi,
Thanks for your awesome work on Electricity Map!

I found one missing locale in PL and decided to submit a translations.

2021-09-05 10:43 UTC, piotrek124-1 requested changes

2021-09-05 10:43 UTC, piotrek124-1 commented on web/locales/pl.json
> +        "lowCarbDescription": "Zawiera nieskoemisyjne i jądrowe źródła energii"
Drobna literówka, powinno być niskoemisyjne

2021-09-05 12:51 UTC, cieciurm commented
Thanks for noticing the typo, @piotrek124-1 ;)

2021-09-05 16:50 UTC, piotrek124-1 approved these changes

2021-09-06 08:39 UTC, skovhus approved these changes

2021-09-06 08:39 UTC, merged