Enable serving live map on app.electricitymap.org
tmrowco/electricitymap-contrib pull request #3379
Opened 2021-09-10 07:29 UTC by corradio

This PR disables the redirect to www from app.electricitymap.org so we can test serving it on both domains.
@skovhus I think it would be good to add some redirect tests here. Do you have any idea of how we could go about this? (also feel free to add the scaffolding directly to the PR)

2021-09-13 09:27 UTC, madsnedergaard commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
Hmm, will this change from `=== live.e` to `!== www.e` affect other subdomains like api.electricitymap.org? 🤔

2021-09-13 10:02 UTC, corradio commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
I don't think so as this node server doesn't serve api.electricitymap.org?

2021-09-13 10:06 UTC, madsnedergaard commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
Okay, let's try it then ¯\\\_(ツ)\_/¯

2021-09-13 10:06 UTC, madsnedergaard approved these changes

2021-09-14 14:47 UTC, corradio commented
I'm puzzled as https://app.electricitymap.org/ is currently NOT redirected..
Any idea why? Maybe it's time to introduce some tests.

2021-09-15 06:40 UTC, madsnedergaard commented
> I'm puzzled as [app.electricitymap.org](https://app.electricitymap.org/) is currently NOT redirected..
> Any idea why?

It's because the redirect logic is currently kinda broken due to `isNonWWW`. That constants says if you're `electricitymap.org` or `live.electricitymap.org`, then you're not `wwww`... So it never captures "app" or anything else.

Here's a quick demo:

<img width="444" alt="Screenshot 2021-09-15 at 08 36 48" src="https://user-images.githubusercontent.com/3296643/133383176-6d56b997-8aa9-48c9-b042-d3f79cda8092.png">

>  Maybe it's time to introduce some tests.

I've been avoiding that as it would be nice to rethink this whole server approach as we've talked about before, but maybe it's better to have a few tests until then :)

2021-09-15 06:41 UTC, madsnedergaard commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
Actually, I think the "includes" usage here will mean it's always evaluating to true!

2021-09-15 06:43 UTC, madsnedergaard commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
Couldn't we just do `const isNonWWW = req.get('host') !== 'www.electricitymap.org';` or would that have other consequences? 🤔

2021-09-15 06:43 UTC, madsnedergaard requested changes
See above comments

2021-09-15 07:31 UTC, corradio commented on web/server.js
> +    || req.get('host') !== 'www.electricitymap.org';
> Actually, I think the "includes" usage here will mean it's always evaluating to true!

Good catch. Why don't we simply remove the redirect for this case then (in order to keep the current behaviour)?
I can just remove the `isNonWWW` from the condition.

2021-09-15 09:21 UTC, corradio commented
Closing this PR as the map can already be served on app.electricitymap.org

2021-09-15 09:21 UTC, closed without merging