Add Nigeria Capacities
tmrowco/electricitymap-contrib pull request #3388
Opened 2021-09-18 21:13 UTC by nessie2013

2021-09-19 17:53 UTC, byronwilliams requested changes

2021-09-19 17:53 UTC, byronwilliams commented on DATA_SOURCES.md
> +- Nigeria: [USAID](https://www.usaid.gov/powerafrica/nigeria)
Change the Nigeria reference to have 2 bullet points. 

* One for the Data source: SO Grid
* One for the Capacity: USAID

2021-10-04 09:36 UTC, skovhus approved these changes

2021-10-04 09:37 UTC, skovhus approved these changes

2021-10-04 09:45 UTC, merged